pipeline {
    agent { dockerfile true }
    environment {
        JENKINS_JOB = 'Testing_pipeline_${BUILD_TAG}'
    }
    stages {
        stage('Build') {
            steps {
                script {
		    echo "Starting Job: ${JENKINS_JOB}"
                    openshift.setLockName(${JENKINS_JOB})
                }
            }
        }
        stage('Run tests') {
            parallel {
                stage('Test run 1') {
                    steps {
                        script {
                            openshift.withCluster(openshift) {
                                openshift.withProject( 'jenkinsdemo' ) {
                                  echo "Hello from project ${openshift.project()} in cluster ${openshift.cluster()}"
                                }
                            }
                        }
                    }
                }

                stage('Test run 2') {
                    steps {
                        script {
                            openshift.withCluster(openshift) {
                                openshift.withProject( 'jenkinsdemo' ) {
                                  echo "Hello from project ${openshift.project()} in cluster ${openshift.cluster()}"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
