pipeline {
    agent {
      kubernetes {
        label podlabel
        yaml """
kind: Pod
metadata:
  name: jenkins-slave
spec:
  containers:
  - name: Abeona
    image: quay.io/bwhorton/jnlp-buildah
    imagePullPolicy: Always
    tty: true
    restartPolicy: Never
"""
      }
    }
    environment {
        JENKINS_JOB = 'Testing_pipeline_${BUILD_TAG}'
    }
    stages {
        stage('Build') {
            steps {
                script {
		    echo "Starting Job: ${JENKINS_JOB}"
                    openshift.setLockName(${JENKINS_JOB})
                }
            }
        }
        stage('Run tests') {
            parallel {
                stage('Test run 1') {
                    steps {
                        script {
                            openshift.withCluster(openshift) {
                                openshift.withProject( 'jenkinsdemo' ) {
                                  echo "Hello from project ${openshift.project()} in cluster ${openshift.cluster()}"
                                }
                            }
                        }
                    }
                }

                stage('Test run 2') {
                    steps {
                        script {
                            openshift.withCluster(openshift) {
                                openshift.withProject( 'jenkinsdemo' ) {
                                  echo "Hello from project ${openshift.project()} in cluster ${openshift.cluster()}"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
